### ISSUE TITLE
test: double-poll-crash failed

### ISSUE THREAD

**Issue by ammarfaizi2** [axboe/liburing#386]
Hi, I got one test failed (double-poll-crash). Any instruction to debug it further?

## Kernel Version
```
ammarfaizi2@integral:~/project/now/liburing$ uname -r
5.13.0-icetea001-12377-gf55966571d5e
```

## Core Dump Inspection
```
[New LWP 1710513]
Core was generated by `./double-poll-crash'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00005586f41fd5d9 in syz_io_uring_submit (a2=0x20000000, a3=0x0, a1=0xffffffffffffffff, a0=0xffffffffffffffff) at double-poll-crash.c:71
71	      (CQ_CQES_OFFSET + cq_ring_entries * SIZEOF_IO_URING_CQE + 63) & ~63;
rax            0xffffffffffffffff  0xffffffffffffffff
rbx            0xffffffff          0xffffffff
rcx            0x10                0x10
rdx            0x0                 0x0
rsi            0x20000000          0x20000000
rdi            0xffffffffffffffff  0xffffffffffffffff
rbp            0x0                 0x0
rsp            0x7ffc5f918200      0x7ffc5f918200
r8             0x0                 0x0
r9             0x7ffc5f917ee6      0x7ffc5f917ee6
r10            0x0                 0x0
r11            0x246               0x246
r12            0x5586f41fd690      0x5586f41fd690
r13            0x0                 0x0
r14            0x0                 0x0
r15            0x0                 0x0
rip            0x5586f41fd5d9      0x5586f41fd5d9 <main+697>
eflags         0x10213             [ CF AF IF RF ]
cs             0x33                0x33
ss             0x2b                0x2b
ds             0x0                 0x0
es             0x0                 0x0
fs             0x0                 0x0
gs             0x0                 0x0
gef➤  backtrace
#0  0x00005586f41fd5d9 in syz_io_uring_submit (a2=0x20000000, a3=0x0, a1=0xffffffffffffffff, a0=0xffffffffffffffff) at double-poll-crash.c:71
#1  main (argc=<optimized out>, argv=<optimized out>) at double-poll-crash.c:174
gef➤  x/10i $rip
=> 0x5586f41fd5d9 <main+697>:	mov    0x10c(%rax),%edx
   0x5586f41fd5df <main+703>:	rep movsl %ds:(%rsi),%es:(%rdi)
   0x5586f41fd5e1 <main+705>:	mov    $0x20450c,%esi
   0x5586f41fd5e6 <main+710>:	shl    $0x4,%edx
   0x5586f41fd5e9 <main+713>:	lea    0x17f(%rdx),%r8d
   0x5586f41fd5f0 <main+720>:	mov    0x40(%rax),%edx
   0x5586f41fd5f3 <main+723>:	and    $0xffffffc0,%r8d
   0x5586f41fd5f7 <main+727>:	mov    %edx,%ecx
   0x5586f41fd5f9 <main+729>:	and    0x100(%rax),%ecx
   0x5586f41fd5ff <main+735>:	add    $0x1,%edx
gef➤  
```

## Full Test Output
```
ammarfaizi2@integral:~/project/now/liburing$ sudo chrt --fifo 99 taskset -c 2,3 make runtests -j2
[sudo] password for ammarfaizi2: 
make[1]: Entering directory '/home/ammarfaizi2/project/now/liburing/src'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/ammarfaizi2/project/now/liburing/src'
make[1]: Entering directory '/home/ammarfaizi2/project/now/liburing/test'
     CC 232c93d07b74-test
make[1]: Leaving directory '/home/ammarfaizi2/project/now/liburing/test'
make[1]: Entering directory '/home/ammarfaizi2/project/now/liburing/examples'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/ammarfaizi2/project/now/liburing/examples'
make[1]: Entering directory '/home/ammarfaizi2/project/now/liburing/test'
Running test 232c93d07b74-test:
Running test 35fa71a030ca-test:
Test 35fa71a030ca-test timed out (may not be a failure)
Running test 500f9fbadef8-test:
Running test 7ad0e4b2f83c-test:
Running test 8a9973408177-test:
Running test 917257daa0fe-test:
Running test a0908ae19763-test:
Running test a4c0b3decb33-test:
Running test accept:
Running test accept-link:
Running test accept-reuse:
Running test accept-test:
Running test across-fork:
Running test splice:
Running test b19062a56726-test:
Running test b5837bd5311d-test:
Running test ce593a6c480a-test:
Running test close-opath:
Running test connect:
Running test cq-full:
Running test cq-overflow:
Running test cq-peek-batch:
Running test cq-ready:
Running test cq-size:
Running test d4ae271dfaae-test:
Running test d77a67ed5f27-test:
Running test defer:
Running test double-poll-crash:
timeout: the monitored command dumped core
./runtests.sh: line 66: 1710512 Segmentation fault      timeout -s INT -k $TIMEOUT $TIMEOUT ./$test_name $dev
Test double-poll-crash failed with ret 139
Running test eeed8b54e0df-test:
Running test eventfd:
Running test eventfd-disable:
Running test eventfd-ring:
Running test fadvise:
Running test fallocate:
Running test fc2a85cb02ef-test:
Test needs failslab/fail_futex/fail_page_alloc enabled, skipped
Running test file-register:
Running test file-update:
Running test files-exit-hang-poll:
Running test files-exit-hang-timeout:
Running test fixed-link:
Running test fsync:
Running test hardlink:
linkat not supported, skipping
Running test io-cancel:
Running test io_uring_enter:
io_uring_enter(3, 1, 0, 4294967295, (nil))
io_uring_enter(-1, 0, 0, 0, (nil))
io_uring_enter(0, 0, 0, 0, (nil))
io_uring_enter(3, 1, 0, 0, (nil))
Allocating 4096 sqes
Submitting 4096 I/Os
Done
Waiting for 4096 events
Reaping 4096 I/Os
Submitting invalid sqe index.
PASS
Running test io_uring_register:
RELIMIT_MEMLOCK: 1431462400 (1431462400)
io_uring_register(-1, 0, (nil), 0)
io_uring_register(3, 0, (nil), 0)
io_uring_register(4, 4294967295, (nil), 0)
io_uring_register(4, 0, 0x7ffc24a1cba0, 1)
io_uring_register(4, 0, 0x7ffc24a1cba0, 1)
io_uring_register(4, 0, 0x7ffc24a1cba0, 1)
Success!
reserve file-backed buffers
io_uring_register(4, 0, 0x7ffc24a1cba0, 1)
io_uring_register(4, 0, 0x7f6bd4bdc010, 1000000)
io_uring_register(4, 0, 0x7f6bd4bdc010, 1024)
Not enough memory for this test, skipping
io_uring_submit:
	opcode: 6
	flags:  0x00000000
	fd:     4
	poll_events: 0x00000005
io_uring_register(4, 2, 0x7ffc24a1caec, 1)
PASS
Running test io_uring_setup:
io_uring_setup(0, 0x7ffc7cc23360), flags: none, feat: none, resv: 0x00000000 0x00000000 0x00000000, sq_thread_cpu: 0
io_uring_setup(1, (nil)), flags: none, feat: none, resv: , sq_thread_cpu: 0
io_uring_setup(1, 0x7ffc7cc23360), flags: none, feat: none, resv: 0x00000001 0x00000001 0x00000001, sq_thread_cpu: 0
io_uring_setup(1, 0x7ffc7cc23360), flags: 0xffffffff, feat: none, resv: 0x00000000 0x00000000 0x00000000, sq_thread_cpu: 0
io_uring_setup(1, 0x7ffc7cc23360), flags: IORING_SETUP_SQ_AFF, feat: none, resv: 0x00000000 0x00000000 0x00000000, sq_thread_cpu: 0
io_uring_setup(1, 0x7ffc7cc23360), flags: IORING_SETUP_SQPOLL|IORING_SETUP_SQ_AFF, feat: none, resv: 0x00000000 0x00000000 0x00000000, sq_thread_cpu: 4
PASS
Running test iopoll:
Running test lfs-openat:
Running test lfs-openat-write:
Running test link:
Running test link-timeout:
Running test link_drain:
Running test madvise:
Running test mkdir:
mkdirat not supported, skipping
Running test multicqes_drain:
Running test nop:
Running test nop-all-sizes:
Running test open-close:
Running test openat2:
Running test personality:
Running test pipe-eof:
Running test pipe-reuse:
Running test poll:
Running test poll-cancel:
Running test poll-cancel-ton:
Running test poll-link:
Running test poll-many:
Running test poll-mshot-update:
Running test poll-ring:
Running test poll-v-poll:
Running test probe:
Running test read-write:
Running test register-restrictions:
Running test rename:
Running test ring-leak:
Running test ring-leak2:
Running test rw_merge_test:
Running test self:
Running test send_recv:
Running test send_recvmsg:
Running test shared-wq:
Running test short-read:
Running test shutdown:
Running test sigfd-deadlock:
Running test socket-rw:
Running test socket-rw-eagain:
Running test sq-full:
Running test sq-poll-dup:
Running test sq-poll-kthread:
Running test sq-poll-share:
Running test sqpoll-disable-exit:
Running test sqpoll-exit-hang:
Running test sqpoll-sleep:
Running test sq-space_left:
Running test stdout:
This is a pipe test
This is a fixed pipe test
Running test submit-reuse:
Running test symlink:
symlinkat not supported, skipping
Running test teardowns:
Running test thread-exit:
Running test timeout:
Running test timeout-new:
Running test timeout-overflow:
Skipping
Running test unlink:
Running test wakeup-hang:
Running test sendmsg_fs_cve:
Running test rsrc_tags:
Running test statx:
Running test sq-full-cpp:
Tests failed:  <double-poll-crash>
make[1]: *** [Makefile:294: runtests] Error 1
make[1]: Leaving directory '/home/ammarfaizi2/project/now/liburing/test'
make: *** [Makefile:23: runtests] Error 2
ammarfaizi2@integral:~/project/now/liburing$ 
```

## Kernel Log
```
ammarfaizi2@integral:/tmp$ sudo dmesg -w
[609639.067429] Running test 232c93d07b74-test:
[609643.550571] Running test 35fa71a030ca-test:
[609703.564942] Running test 500f9fbadef8-test:
[609704.540044] Running test 7ad0e4b2f83c-test:
[609705.568622] Running test 8a9973408177-test:
[609706.681860] Running test 917257daa0fe-test:
[609706.711771] Running test a0908ae19763-test:
[609706.741700] Running test a4c0b3decb33-test:
[609714.311394] Running test accept:
[609715.913573] Running test accept-link:
[609716.140992] Running test accept-reuse:
[609716.172271] Running test accept-test:
[609716.212216] Running test across-fork:
[609716.243871] Running test splice:
[609716.278621] Running test b19062a56726-test:
[609716.308796] Running test b5837bd5311d-test:
[609716.351165] Running test ce593a6c480a-test:
[609717.486826] Running test close-opath:
[609717.545251] Running test connect:
[609717.556185] TCP: request_sock_TCP: Possible SYN flooding on port 9849. Sending cookies.  Check SNMP counters.
[609717.589865] Running test cq-full:
[609717.632865] Running test cq-overflow:
[609728.337910] Running test cq-peek-batch:
[609728.394812] Running test cq-ready:
[609728.423449] Running test cq-size:
[609728.460897] Running test d4ae271dfaae-test:
[609728.567282] Running test d77a67ed5f27-test:
[609728.745265] Running test defer:
[609731.776272] Running test double-poll-crash:
[609731.787827] double-poll-cra[1710513]: segfault at 10b ip 00005586f41fd5d9 sp 00007ffc5f918200 error 4 in double-poll-crash[5586f41fd000+2000]
[609731.787862] Code: 00 00 20 00 c6 04 25 3d 00 00 20 00 c6 04 25 3e 00 00 20 00 c6 04 25 3f 00 00 20 00 48 8b 05 56 3a 00 00 48 8b 3d 57 3a 00 00 <8b> 90 0c 01 00 00 f3 a5 be 0c 45 20 00 c1 e2 04 44 8d 82 7f 01 00
[609732.408609] Running test eeed8b54e0df-test:
[609732.517819] Running test eventfd:
[609732.568219] Running test eventfd-disable:
[609732.614056] Running test eventfd-ring:
[609732.679745] Running test fadvise:
[609732.837190] Running test fallocate:
[609732.919129] Running test fc2a85cb02ef-test:
[609732.950206] Running test file-register:
[609750.620247] Running test file-update:
[609753.777112] Running test files-exit-hang-poll:
[609754.805853] Running test files-exit-hang-timeout:
[609755.835783] Running test fixed-link:
[609755.905270] Running test fsync:
[609756.083119] Running test hardlink:
[609756.114440] Running test io-cancel:
[609758.424896] Running test io_uring_enter:
[609758.517956] Running test io_uring_register:
[609761.720250] Running test io_uring_setup:
[609761.784124] Running test iopoll:
[609774.823662] Running test lfs-openat:
[609774.854554] Running test lfs-openat-write:
[609774.883126] Running test link:
[609774.949311] Running test link-timeout:
[609777.296407] Running test link_drain:
[609777.705222] Running test madvise:
[609777.851584] Running test mkdir:
[609777.881736] Running test multicqes_drain:
[609822.919251] Running test nop:
[609822.947557] Running test nop-all-sizes:
[609823.005468] Running test open-close:
[609823.165797] Running test openat2:
[609823.291850] Running test personality:
[609823.324986] Running test pipe-eof:
[609823.356273] Running test pipe-reuse:
[609823.386430] Running test poll:
[609823.418287] Running test poll-cancel:
[609823.450203] Running test poll-cancel-ton:
[609823.606483] Running test poll-link:
[609823.836618] Running test poll-many:
[609830.921782] Running test poll-mshot-update:
[609836.461596] Running test poll-ring:
[609836.490338] Running test poll-v-poll:
[609836.924581] Running test probe:
[609836.954827] Running test read-write:
[609891.270193] Running test register-restrictions:
[609891.528917] Running test rename:
[609891.559089] Running test ring-leak:
[609891.612420] Running test ring-leak2:
[609892.642080] Running test rw_merge_test:
[609892.698676] Running test self:
[609892.730913] Running test send_recv:
[609892.764852] Running test send_recvmsg:
[609892.797425] Running test shared-wq:
[609892.829936] Running test short-read:
[609892.910663] Running test shutdown:
[609892.943620] Running test sigfd-deadlock:
[609892.976659] Running test socket-rw:
[609893.008867] Running test socket-rw-eagain:
[609893.042076] Running test sq-full:
[609893.073407] Running test sq-poll-dup:
[609896.567683] Running test sq-poll-kthread:
[609898.667982] Running test sq-poll-share:
[609904.578231] Running test sqpoll-disable-exit:
[609905.376333] Running test sqpoll-exit-hang:
[609906.447651] Running test sqpoll-sleep:
[609906.480219] Running test sq-space_left:
[609906.511768] Running test stdout:
[609908.599986] Running test submit-reuse:
[609911.918775] Running test symlink:
[609911.958831] Running test teardowns:
[609912.054809] Running test thread-exit:
[609912.138001] Running test timeout:
[609918.192086] Running test timeout-new:
[609920.635429] Running test timeout-overflow:
[609920.666904] Running test unlink:
[609920.698565] Running test wakeup-hang:
[609922.731544] Running test sendmsg_fs_cve:
[609922.764304] Running test rsrc_tags:
[609944.765269] Running test statx:
[609944.847441] Running test sq-full-cpp:
```

**Comment by ammarfaizi2** [comment]
This is strange, sometimes it fails, sometimes it passes.

**Comment by ammarfaizi2** [comment]
Seems to be a false positive bug, I can't reproduce it anymore. Regardless the test is autogenerated by syzkaller, which looks prone to me, the `mmap()` call don't have any fail check neither, if those fail, the deref will be illegal and might fault.. I am closing this.
